#!/bin/bash

IMAGESNORT="mateusmantoan/snort:1.0"
IMAGESQUID="mateusmantoan/squid:1.0"
IMAGETCPDUMP="mateusmantoan/tcpdump:1.0"
IMAGENMAP="mateusmantoan/nmap:1.0"
INT0="wlp3s0"
INT1="eth1"

clear
alias iptables="/sbin/iptables"

touch /etc/jubarte/status
touch /etc/jubarte/var/dumpall

#if [ cat "/etc/jubarte/status" != 0]

function INICIO () {
    clear
    echo "   ___       _                _        ______ _                        _ _ "
    echo "  |_  |     | |              | |       |  ___(_)                      | | |"
    echo "    | |_   _| |__   __ _ _ __| |_ ___  | |_   _ _ __ _____      ____ _| | |"
    echo "    | | | | | '_ \ / _| | |__| __/ _ \ |  _| | | |__/ _ \ \ /\ / / _| | | |"
    echo "/\__/ / |_| | |_) | (_| | |  | ||  __/ | |   | | | |  __/\ V  V / (_| | | |"
    echo "\____/ \__,_|_.__/ \__,_|_|   \__\___| \_|   |_|_|  \___| \_/\_/ \__,_|_|_|"
    echo
    echo COMMAND LINE INTERFACE
    echo
    #echo Type 1 to manage hosts
    echo Type 2 to manage iptaples rules
    #echo Type 3 to configure snort
    #echo Type 4 to configure squid
    echo Type 5 to use tcpdump
    echo Type 6 to use nmap
    echo
    echo Type 0 to close CLI
    read option
    
    if [ $option = 1 ]
    then
        HOSTS
    elif [ $option = 2 ]
    then
        IPTABLES
    elif [ $option = 3 ]
    then
        SNORT
    elif [ $option = 4 ]
    then
        SQUID
    elif [ $option = 5 ]
    then
        TCPDUMP
    elif [ $option = 6 ]
    then
        NMAP
    elif [ $option = 0 ]
    then
        clear
        exit 0    
    else
        echo invalid option, try again
        sleep 2
        INICIO
    fi
}
 
#HOSTS FUNCTIONS

function HOSTS () {
    clear
    echo MANAGER HOSTS
    echo Actual hosts:
    cat /etc/jubarte/hostsfile
    echo \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
    echo Type 1 to include hosts
    echo Type 2 to remove hosts
    echo Type 0 to back
    read option
    if [ $option = 1 ]
    then
        HOSTS_ADICIONAR
    elif [ $option = 2 ]
    then
        HOSTS_REMOVER
    elif [ $option = 0 ]
    then
        INICIO
    else
        echo invalid option, try again
        sleep 1
        HOSTS
    fi
}

function HOSTS_ADICIONAR () {
    echo Type the new IP
    echo Type 9 to back to HOSTS MENU
    read IP
    ipvalido=$(echo $IP | egrep '^(([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$')
    if [ $IP = 9 ]
    then
        HOSTS
    elif [ "$ipvalido" != "" ]
        then
        JOIN_TOKEN=`docker swarm join-token manager | grep swarm`
        sshpass -p "toor" ssh root@$IP "$JOIN_TOKEN"
        sshpass -p "toor" ssh root@$IP "iptables-restore < /etc/jubarte/iptables-actual"
        sshpass -p "toor" ssh root@$IP "rm -rf /etc/jubarte"
        sshpass -p "toor" scp -r /etc/jubarte root@$IP:/etc/
        for server in $(cat /etc/jubarte/hostsfile)
        do
            sshpass -p "toor" ssh root@$server "echo $IP >> /etc/jubarte/hostsfile"
            done
        echo IP included on cluster
    else
        echo Invalid IP, verify again
        sleep 1
        HOSTS_ADICIONAR
    fi    
}

function HOSTS_REMOVER () {
    echo Type the IP will be removed
    echo Type 9 to back to HOSTS MENU
    read IP
    ipvalido=$(echo $IP | egrep '^(([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$')
    if [ $IP = 9 ]
    then
        HOSTS
    elif [ "$ipvalido" != "" ]
        then
        for server in $(cat /etc/jubarte/hostsfile)
        do
            sshpass -p "toor" ssh root@$server "sed -i /^$IP/d /etc/jubarte/hostsfile"
            done
        echo IP removed of cluster
    else
        echo Invalid IP, verify again
        echo 
        HOSTS_REMOVER
    fi    
}

#HOSTS IPTABLES

function IPTABLES () {
    clear
    echo IPTABLES MANAGER
    echo \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
    echo Type 1 to apply rules
    echo Type 2 to show actual rules
    echo Type 3 to reset rules
    echo Type 0 to back
    read option
    if [ $option = 1 ]
    then
        IPTABLES_APPREGRAS
    elif [ $option = 2 ]
    then
        IPTABLES_VERREGRAS
    elif [ $option = 3 ]
    then
        IPTABLES_ZERARREGRAS
    elif [ $option = 0 ]
    then
        INICIO    
    else
        echo invalid option, try again
        sleep 1
        IPTABLES
    fi
}

function IPTABLES_ADDREGRAS () {
    clear
    echo Type the rule to apply on cluster
    echo Type 9 to back to iptables menu
    read RULE
    if [ $RULE = 9 ]
    then
        IPTABLES
    else
    for server in $(cat /etc/jubarte/hostsfile)
    do
        sshpass -p "toor" ssh root@$server "$RULE"
        sshpass -p "toor" ssh root@$server "/sbin/iptables-save >> /etc/jubarte/iptables-actual_TEMP"
        sshpass -p "toor" ssh root@$server "rm /etc/jubarte/iptables-actual"
        sshpass -p "toor" ssh root@$server "mv /etc/jubarte/iptables-actual_TEMP /etc/jubarte/iptables-actual"
        done
        
    echo rule included on cluster
    sleep 1
    fi
    IPTABLES
}

function IPTABLES_VERREGRAS () {
    clear
    iptables -L
    echo
    echo
    echo Type ENTER to back to iptables menu
    read RULE
    IPTABLES
}

function IPTABLES_ZERARREGRAS () {
    clear
    iptables-restore < /etc/jubarte/iptables-clean
    echo 
    echo IPtables rules restored
    echo
    echo Type ENTER to back to iptables menu
    read RULE
    IPTABLES
}

#HOSTS TCPDUMP

function TCPDUMP () {
    clear
    echo TCPDUMP MANAGER
    echo \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
    echo Type 1 to sniff traffic
    echo
    echo ALL LOGS OF TCPDUMP ARE IN /etc/jubarte/log/tcpdump/
    echo 
    DUMPALLSTATUS=`cat /etc/jubarte/var/dumpall`
    if [ "$DUMPALLSTATUS" != 1 ]
    then
        echo Type 2 to start dump on all cluster
    else
        echo The dump of all cluster are operating now
    fi
    echo Type 0 to back
    read option
    if [ $option = 1 ]
    then
        TCPDUMP_SNIFF
    elif [ $option = 2 ]
    then
        TCPDUMP_ALL_START
    elif [ $option = 0 ]
    then
        INICIO    
    else
        echo invalid option, try again
        sleep 1
        TCPDUMP
    fi 
}

function TCPDUMP_SNIFF () {
    echo Type 1 to sniff cluster traffic now
    echo Type 2 to create sniff rules
    echo Type 3 to see the actual rules
    echo Type 4 to remove sniff rules
    echo Type 0 to back tcpdump options
    read option
    
    if [ $option = 1 ]
    then
        TCPDUMP_SNIFF_NOW
    elif [ $option = 2 ]
    then
        TCPDUMP_SNIFF_RULES
    elif [ $option = 3 ]
    then
        TCPDUMP_SEE_RULES
    elif [ $option = 4 ]
    then
        TCPDUMP_REMOVE_RULES
    elif [ $option = 0 ]
    then
        TCPDUMP    
    else
        echo invalid option, try again
        sleep 1
        TCPDUMP_SNIFF
    fi 
}

function TCPDUMP_SNIFF_NOW () {
    echo Type the tcpdump command
    echo *the interfaces of firewall are $INT0 and $INT1
    echo **Stop capture with Ctrl+C
    read TCPDUMPCMD
    docker run --net host --rm ${IMAGETCPDUMP} ${TCPDUMPCMD}
    echo
    echo
    echo
    echo Type enter to back
    clear
    TCPDUMP    
}

function TCPDUMP_SNIFF_RULES () {
    echo "Type the name of rule (one string, no spaces)"
    read NAME
    TCPDUMPRULENAME=`echo "$NAME" | sed "s, ,,g"`
    
    echo "$TCPDUMPRULENAME | $RULE" >> /etc/jubarte/var/tcpdumprules
    echo Type the tcpdump command
    echo *the interfaces of firewall are ${INT0} and ${INT1}
    read TCPDUMPCMD
    `docker run -itd --restart always --net host --name ${TCPDUMPRULENAME} --volume /etc/jubarte/logs/tcpdump/:/root/logs/tcpdump/ ${IMAGETCPDUMP} ${TCPDUMPCMD} -w /root/logs/tcpdump/${TCPDUMPRULENAME}.pcap`
    
}

function TCPDUMP_SEE_RULES () {
    echo -n "Actual rules\n"
    cat /etc/jubarte/var/tcpdumprules
}

function TCPDUMP_REMOVE_RULES () {
    echo Type the name of rule to be removed
    read NAME
    docker rm -f ${NAME}
    sed -i '/${NAME}/d' /etc/jubarte/var/tcpdumprules
    
}


function TCPDUMP_ALL_START () {
    docker run -itd --restart always --net host --name dumpall --volume /etc/jubarte/logs/tcpdump/:/root/logs/tcpdump/ ${IMAGETCPDUMP} tcpdump -vvv -i ${INT0} -w /root/logs/tcpdump/dumpall.pcap
    echo 1 > /etc/jubarte/var/dumpall
}

function SNORT () {
    clear
    echo SNORT
    echo \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
    if [ `cat /etc/jubarte/snort-status` != 1 ]
    then
    SNORT_INSTALAR    
    fi
    echo Type 1 to 
    echo Type 2 to 
    echo Type 3 to 
    echo Type 0 to back
    read option
    if [ $option = 1 ]
    then
        SNORT_
    elif [ $option = 2 ]
    then
        SNORT_
    elif [ $option = 3 ]
    then
        SNORT_
    elif [ $option = 0 ]
    then
        INICIO    
    else
        echo invalid option, try again
        sleep 1
        SNORT
    fi
}

function SNORT_INSTALAR () {
    echo Type 1 to install snort on cluster
    echo Type 0 to back
    read option
    if [ $option = 1 ]
    then
        docker service create -td --network host --mode global --name snort $IMAGESNORT
        echo "1" > /etc/jubarte/snort-status
    elif [ $option = 0 ]
    then
        INICIO    
    else
        echo invalid option, try again
        sleep 1
        SNORT_INSTALAR
    fi
}
function SQUID () {
    clear
    echo SQUID
    echo \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
    if [ `` != 1 ]
    then
    SQUID_INSTALAR    
    fi
    echo Type 1 to 
    echo Type 2 to 
    echo Type 3 to 
    echo Type 0 to back
    read option
    if [ $option = 1 ]
    then
        SNORT_
    elif [ $option = 2 ]
    then
        SNORT_
    elif [ $option = 3 ]
    then
        SNORT_
    elif [ $option = 0 ]
    then
        INICIO    
    else
        echo invalid option, try again
        sleep 1
        SNORT
    fi
}

function SNORT_INSTALAR () {
    echo Type 1 to install the squid on cluster
    echo Type 0 to back
    read option
    if [ $option = 1 ]
    then
        docker service create -td --network host --mode global --name snort $IMAGESQUID
        echo "1" > /etc/jubarte/squid-status
    elif [ $option = 0 ]
    then
        INICIO    
    else
        echo invalid option, try again
        sleep 1
        SQUID_INSTALAR
    fi 

}

#`docker swarm init --advertise-addr $(hostname -I | cut -d " " -f 1)`

INICIO
